// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Sprint3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sprint3() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(794, 817));
    driver.findElement(By.cssSelector(".fa-user-doctor")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("123456789");
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).sendKeys("medico1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("añadir")).click();
    driver.findElement(By.id("inlineFormInputGroup")).click();
    driver.findElement(By.id("inlineFormInputGroup")).sendKeys("20");
    driver.findElement(By.cssSelector(".col-auto:nth-child(2) #inlineFormInputGroup")).click();
    driver.findElement(By.cssSelector(".col-auto:nth-child(2) #inlineFormInputGroup")).sendKeys("Carlos Perez");
    driver.findElement(By.cssSelector(".col-auto:nth-child(3) #inlineFormInputGroup")).click();
    driver.findElement(By.cssSelector(".col-auto:nth-child(3) #inlineFormInputGroup")).sendKeys("12345678Q");
    driver.findElement(By.cssSelector(".col-auto:nth-child(4) #inlineFormInputGroup")).click();
    driver.findElement(By.cssSelector(".col-auto:nth-child(4) #inlineFormInputGroup")).sendKeys("Análisis");
    driver.findElement(By.cssSelector(".col-auto:nth-child(5) #inlineFormInputGroup")).click();
    driver.findElement(By.cssSelector(".col-auto:nth-child(5) #inlineFormInputGroup")).sendKeys("14:03");
    driver.findElement(By.cssSelector(".col-auto:nth-child(5) #inlineFormInputGroup")).sendKeys("14:30");
    driver.findElement(By.cssSelector(".col-auto:nth-child(6) #inlineFormInputGroup")).sendKeys("0002-05-11");
    driver.findElement(By.cssSelector(".col-auto:nth-child(6) #inlineFormInputGroup")).sendKeys("0020-05-11");
    driver.findElement(By.cssSelector(".col-auto:nth-child(6) #inlineFormInputGroup")).sendKeys("0202-05-11");
    driver.findElement(By.cssSelector(".col-auto:nth-child(6) #inlineFormInputGroup")).sendKeys("2022-05-11");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".d-inline-block")).click();
    driver.findElement(By.cssSelector(".fa-hospital-user")).click();
    driver.findElement(By.id("input")).click();
    driver.findElement(By.id("input")).sendKeys("12345678Q");
    driver.findElement(By.linkText("Aceptar")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .svg-inline--fa")).click();
    driver.findElement(By.id("btn")).click();
    driver.findElement(By.cssSelector(".fa-user-doctor > path")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("123456789");
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).sendKeys("medico1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(10) .bnt")).click();
    driver.findElement(By.cssSelector(".d-inline-block")).click();
    driver.findElement(By.cssSelector(".fa-display")).click();
    driver.findElement(By.cssSelector(".d-inline-block")).click();
  }
}
